import logging
from apscheduler.schedulers.blocking import BlockingScheduler
from apscheduler.triggers.cron import CronTrigger
from apscheduler.triggers.interval import IntervalTrigger
from datetime import datetime, timedelta
from tasks.prewarn_h2h import PrewarmCacheWorker
from tasks.live_matches import LiveWorker 
from dotenv import load_dotenv
import os

# Configure application-level logging
logging.basicConfig(level=logging.INFO, format='[%(asctime)s] %(levelname)s - %(message)s')
logger = logging.getLogger('Orchestrator')

load_dotenv()
# Fallback to 5 minutes if the environment variable is not set
minutes_interval = int(os.getenv("WORKER_INTERVAL_MINUTES", 5))

def start_orchestrator():
    """
    Initializes and starts the central job scheduler (Orchestrator).
    
    This orchestrator is responsible for managing background tasks using APScheduler.
    It guarantees that jobs like pre-warming caches, scouting daily schedules, 
    and fetching live match updates run at precise times without overlapping.
    """
    logger.info("🚀 Starting Orchestrator...")

    # max_instances=1 prevents a job from executing again if the previous run hasn't finished.
    scheduler = BlockingScheduler(job_defaults={'max_instances': 1})
    
    # Initialize the worker instances
    live_worker = LiveWorker()
    prewarm_worker = PrewarmCacheWorker()

    # ==========================================
    # TASK 1: H2H Cache Pre-warming
    # ==========================================
    # Purpose: Fetches and caches Head-to-Head (H2H) statistics for upcoming matches.
    # Execution: Runs once daily at 3:00 AM local time.
    # Why: This runs during extreme off-peak hours to prevent hitting API rate limits
    # and ensures Redis is fully populated before users wake up to check the app.
    scheduler.add_job(
        prewarm_worker.prewarm_matches,
        CronTrigger(hour=3, minute=0, timezone='America/Mexico_City'),
        id='h2h_prewarm_worker',
        name='H2H Cache Prewarming Worker',
        replace_existing=True
    )

    # ==========================================
    # TASK 2: Daily Schedule Scout
    # ==========================================
    # Purpose: Queries the sports API to find out exactly which matches are playing today
    # and calculates the active time windows for live polling.
    # Execution: Runs once daily at 6:00 AM local time.
    scheduler.add_job(
        live_worker.run_scout,
        CronTrigger(hour=6, minute=0, timezone='America/Mexico_City'),
        id='scout_worker',
        name='Scout Worker',
        replace_existing=True
    )

    # ==========================================
    # TASK 3: Live Match Updater
    # ==========================================
    # Purpose: Polls the sports API for live scores, elapsed time, and match status.
    # Execution: Runs on a continuous interval (e.g., every 5 minutes) defined in the .env file.
    # Note: The underlying worker logic determines if it should actually fetch data 
    # based on the active windows generated by the Scout.
    scheduler.add_job(
        live_worker.run_live_update,
        IntervalTrigger(minutes=minutes_interval),
        id='live_update_worker',
        name='Live Update Worker',
        replace_existing=True
    )

    logging.info("✅ Orchestrator configuration complete.")
    
    # Run the scout immediately on startup to ensure we have today's schedule 
    # in case the server is restarted during the day.
    logger.info("Executing initial daily scout...")
    live_worker.run_scout()

    try:
        # Start the blocking scheduler (this keeps the script running indefinitely)
        scheduler.start()
    except (KeyboardInterrupt, SystemExit):
        logging.info("🛑 Shutting down Orchestrator safely...")

if __name__ == "__main__":
    start_orchestrator()