"""replace booleans with bet_type

Revision ID: 223a34deb5d4
Revises: 3baf6cf52ab7
Create Date: 2026-01-01 14:56:49.152779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223a34deb5d4'
down_revision: Union[str, Sequence[str], None] = '3baf6cf52ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_tickets', sa.Column('bet_type', sa.String(), nullable=True))
    
    op.execute("UPDATE betting_tickets SET bet_type = 'parlay' WHERE is_parley = True")
    op.execute("UPDATE betting_tickets SET bet_type = 'crear_apuesta' WHERE is_create_bet = True")

    op.drop_column('betting_tickets', 'is_parley')
    op.drop_column('betting_tickets', 'is_create_bet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_tickets', sa.Column('is_create_bet', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('betting_tickets', sa.Column('is_parley', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('betting_tickets', 'bet_type')
    # ### end Alembic commands ###
