"""create betting tickets table

Revision ID: 3c8fe89330b4
Revises: 0f262f6a5beb
Create Date: 2025-12-28 14:02:20.705538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8fe89330b4'
down_revision: Union[str, Sequence[str], None] = '0f262f6a5beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betting_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('pick', sa.String(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=True),
    sa.Column('stake', sa.Float(), nullable=True),
    sa.Column('payout', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bet_description', sa.String(), nullable=True),
    sa.Column('is_parley', sa.Boolean(), nullable=True),
    sa.Column('is_create_bet', sa.Boolean(), nullable=True),
    sa.Column('match_datetime', sa.DateTime(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('studied', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_betting_tickets_id'), 'betting_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_betting_tickets_ticket_id'), 'betting_tickets', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_betting_tickets_ticket_id'), table_name='betting_tickets')
    op.drop_index(op.f('ix_betting_tickets_id'), table_name='betting_tickets')
    op.drop_table('betting_tickets')
    # ### end Alembic commands ###
