"""change match_datetime to timestamptz

Revision ID: 6af86da203be
Revises: ebdb22b1e091
Create Date: 2026-01-01 21:39:09.829470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af86da203be'
down_revision: Union[str, Sequence[str], None] = 'ebdb22b1e091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_tickets', sa.Column('match_name', sa.String(), nullable=True))
    op.alter_column('betting_tickets', 'match_datetime',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('betting_tickets', 'match_datetime',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('betting_tickets', 'match_name')
    # ### end Alembic commands ###
