"""Change ForeignKey

Revision ID: 6b6a6f0a9e08
Revises: 0584bdde8382
Create Date: 2026-01-09 00:19:15.043939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6a6f0a9e08'
down_revision: Union[str, Sequence[str], None] = '0584bdde8382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('leagues_country_name_fkey'), 'leagues', type_='foreignkey')
    op.create_foreign_key(None, 'leagues', 'countries', ['country_id'], ['id'])
    op.drop_column('leagues', 'country_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_foreign_key(op.f('leagues_country_name_fkey'), 'leagues', 'countries', ['country_name'], ['name'])
    op.drop_column('leagues', 'country_id')
    # ### end Alembic commands ###
