"""add sport and playdoit_champ_id to leagues

Revision ID: 760e417b7ade
Revises: 971ee86c286f
Create Date: 2026-09-26 19:51:08.928495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760e417b7ade'
down_revision: Union[str, Sequence[str], None] = '971ee86c286f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('sport', sa.String(), nullable=True))
    op.add_column('leagues', sa.Column('playdoit_champ_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_leagues_playdoit_champ_id'), 'leagues', ['playdoit_champ_id'], unique=True)
    op.create_index(op.f('ix_leagues_sport'), 'leagues', ['sport'], unique=False)
    # ### end Alembic commands ###

    # Backfill: todas las ligas existentes hoy vienen de API-Football, es decir fútbol.
    op.execute("UPDATE leagues SET sport = 'futbol' WHERE sport IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leagues_sport'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_playdoit_champ_id'), table_name='leagues')
    op.drop_column('leagues', 'playdoit_champ_id')
    op.drop_column('leagues', 'sport')
    # ### end Alembic commands ###
