"""make fixture_lineups player_id nullable

Revision ID: a12b3672405b
Revises: 0926e8ce1a8a
Create Date: 2026-05-10 12:24:02.138446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12b3672405b'
down_revision: Union[str, Sequence[str], None] = '0926e8ce1a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixture_lineups', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fixture_lineups', 'player_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fixture_lineups', 'player_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fixture_lineups', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
