"""create countries table and link to leagues

Revision ID: b1eb193e4c27
Revises: b5f384854b4f
Create Date: 2026-01-08 23:34:39.206495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1eb193e4c27'
down_revision: Union[str, Sequence[str], None] = 'b5f384854b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('countries', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='id::integer')
    op.alter_column('countries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.add_column('leagues', sa.Column('country_name', sa.String(), nullable=True))
    op.drop_index(op.f('ix_leagues_country_id'), table_name='leagues')
    op.create_foreign_key(None, 'leagues', 'countries', ['country_name'], ['name'])
    op.drop_column('leagues', 'country_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('country_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leagues', type_='foreignkey')
    op.create_index(op.f('ix_leagues_country_id'), 'leagues', ['country_id'], unique=False)
    op.drop_column('leagues', 'country_name')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.alter_column('countries', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('countries', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###