"""change match_datetime to timestamptz

Revision ID: ebdb22b1e091
Revises: 084965cbbba9
Create Date: 2026-01-01 21:36:24.841638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdb22b1e091'
down_revision: Union[str, Sequence[str], None] = '084965cbbba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betting_tickets', 'match_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_tickets', sa.Column('match_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
